# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoordapp', '0003_auto_20171005_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcoorduserinteractionmodel',
            name='dummy',
            field=models.CharField(default='mytest', max_length=500),
        ),
    ]
